import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Layout/Header";
import Footer from "@/Layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
      style={{
        // @ts-ignore
        "--font-primary": '"Times New Roman", Times, serif',
        "--font-secondary": '"Candara", Calibri, Segoe, "Segoe UI", Optima',
        "--font-manrope": '"Manrope", sans-serif',
        "--font-arial": 'Arial, sans-serif'
      }}
    >
      <body className="min-h-full flex flex-col">
        <Header />

        <main className="grow">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
